version: '3'
services:
  backend:
    build:
      context: docker/development/
    image: scraper-backend-bot:latest
    container_name: scraper-backend-bot
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DEBUG=True
    command: python app/main.py